services:
  web:
    image: nginx
    container_name: sportscraper-web
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    container_name: sportscraper-backend
    build:
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    restart: always
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - .:/src
    depends_on:
      -  mongodb

  mongodb:
    image: mongo:6-jammy
    container_name: sportscraper-db
    ports:
      - '27117:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod", "--auth", "--config", "/etc/mongod.conf"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  dbdata6:
